# docker compose file for running on a single-server deployment
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  react-gol:
    image: mattld/react-gol
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - VIRTUAL_PORT=8080
